all: struct heures pointeurs pointeursbis pointeurster

struct: struct.c
	gcc -Wall -pedantic -ansi struct.c -o struct

chaines: chaines.c
	gcc -Wall -pedantic -ansi chaines.c -o chaines

heures: heures.c
	gcc -Wall -pedantic -ansi heures.c -o heures

pointeurs: pointeurs.c
	gcc -Wall -pedantic -ansi pointeurs.c -o pointeurs

pointeursbis: pointeursbis.c
	gcc -Wall -pedantic -ansi pointeursbis.c -o pointeursbis

pointeurster: pointeurster.c
	gcc -Wall -pedantic -ansi pointeurster.c -o pointeurster